// relay_transport.proto
// =====================================================================
// Qubes Air 跨机传输：本地 sys-relay ↔ 远端 Remote-Relay 的 gRPC 双向流。
//
// 【架构】阶段 T（见 docs/roadmap-to-production.md、docs/grpc-transport-design.md）
//   - 本地 relay 作为 gRPC 客户端【主动出站】建连到远端 Remote-Relay 的 server，
//     建立一条长连接【双向流】(Tunnel)。零入站：远端不需要任何入站端口，
//     家庭 NAT 后可用（relay 只出站、不监听）。
//   - 一条 Tunnel 上用 request_id 多路复用多个 qrexec 调用（正向 + 反向回程共用）。
//   - 认证：mTLS（客户端证书 + 服务端证书），证书/私钥存 vault-cloud，
//     用时经 qrexec ask 下发（替代原 relay SSH 私钥）。[TODO 实现]
//
// 【安全模型不变】两侧 dom0 各校验一次：
//   - 正向：本地 dom0 policy A/B 已放行并改写后，请求才进入本 Tunnel；
//     远端 Remote-Relay 收到后经【远端 dom0/policy 再校验】才交 qrexec-client-vm。
//   - 反向（远端→本地，如取 vault 凭据）：帧经 Tunnel 回到本地 relay，
//     必须再过【本地 dom0 policy C：ask】才执行。Relay 不得直达 dom0。
//   → 传输层只搬运帧，不做授权决策；授权始终在两侧 dom0。
// =====================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: relay_transport.proto

package relaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayTransport_Tunnel_FullMethodName = "/qubesair.transport.v1.RelayTransport/Tunnel"
)

// RelayTransportClient is the client API for RelayTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RelayTransport：本地 relay（client）与远端 Remote-Relay（server）之间的传输服务。
type RelayTransportClient interface {
	// Tunnel：一条长连接双向流。client（本地 relay）主动出站建立。
	// 双向：正向 qrexec 调用与反向回程帧都在这一条流上，用 request_id 区分与复用。
	Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type relayTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayTransportClient(cc grpc.ClientConnInterface) RelayTransportClient {
	return &relayTransportClient{cc}
}

func (c *relayTransportClient) Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RelayTransport_ServiceDesc.Streams[0], RelayTransport_Tunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayTransport_TunnelClient = grpc.BidiStreamingClient[Frame, Frame]

// RelayTransportServer is the server API for RelayTransport service.
// All implementations must embed UnimplementedRelayTransportServer
// for forward compatibility.
//
// RelayTransport：本地 relay（client）与远端 Remote-Relay（server）之间的传输服务。
type RelayTransportServer interface {
	// Tunnel：一条长连接双向流。client（本地 relay）主动出站建立。
	// 双向：正向 qrexec 调用与反向回程帧都在这一条流上，用 request_id 区分与复用。
	Tunnel(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedRelayTransportServer()
}

// UnimplementedRelayTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayTransportServer struct{}

func (UnimplementedRelayTransportServer) Tunnel(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Tunnel not implemented")
}
func (UnimplementedRelayTransportServer) mustEmbedUnimplementedRelayTransportServer() {}
func (UnimplementedRelayTransportServer) testEmbeddedByValue()                        {}

// UnsafeRelayTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayTransportServer will
// result in compilation errors.
type UnsafeRelayTransportServer interface {
	mustEmbedUnimplementedRelayTransportServer()
}

func RegisterRelayTransportServer(s grpc.ServiceRegistrar, srv RelayTransportServer) {
	// If the following call panics, it indicates UnimplementedRelayTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayTransport_ServiceDesc, srv)
}

func _RelayTransport_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayTransportServer).Tunnel(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayTransport_TunnelServer = grpc.BidiStreamingServer[Frame, Frame]

// RelayTransport_ServiceDesc is the grpc.ServiceDesc for RelayTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubesair.transport.v1.RelayTransport",
	HandlerType: (*RelayTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tunnel",
			Handler:       _RelayTransport_Tunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "relay_transport.proto",
}
