// relay_transport.proto
// =====================================================================
// Qubes Air 跨机传输：本地 sys-relay ↔ 远端 Remote-Relay 的 gRPC 双向流。
//
// 【架构】阶段 T（见 docs/roadmap-to-production.md、docs/grpc-transport-design.md）
//   - 本地 relay 作为 gRPC 客户端【主动出站】建连到远端 Remote-Relay 的 server，
//     建立一条长连接【双向流】(Tunnel)。零入站：远端不需要任何入站端口，
//     家庭 NAT 后可用（relay 只出站、不监听）。
//   - 一条 Tunnel 上用 request_id 多路复用多个 qrexec 调用（正向 + 反向回程共用）。
//   - 认证：mTLS（客户端证书 + 服务端证书），证书/私钥存 vault-cloud，
//     用时经 qrexec ask 下发（替代原 relay SSH 私钥）。[TODO 实现]
//
// 【安全模型不变】两侧 dom0 各校验一次：
//   - 正向：本地 dom0 policy A/B 已放行并改写后，请求才进入本 Tunnel；
//     远端 Remote-Relay 收到后经【远端 dom0/policy 再校验】才交 qrexec-client-vm。
//   - 反向（远端→本地，如取 vault 凭据）：帧经 Tunnel 回到本地 relay，
//     必须再过【本地 dom0 policy C：ask】才执行。Relay 不得直达 dom0。
//   → 传输层只搬运帧，不做授权决策；授权始终在两侧 dom0。
// =====================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: relay_transport.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction：调用发起方向。决定该 request_id 属于正向还是反向回程，
// 以及落到远端后要再过哪一侧 dom0 policy。
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	// 正向：本地 → 远端。本地 dom0 已校验；远端 dom0/policy 再校验后执行。
	Direction_LOCAL_TO_REMOTE Direction = 1
	// 反向回程：远端 → 本地（如远端取本地 vault 凭据）。
	// 回到本地必须过本地 dom0 policy C（ask）。
	Direction_REMOTE_TO_LOCAL Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "LOCAL_TO_REMOTE",
		2: "REMOTE_TO_LOCAL",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"LOCAL_TO_REMOTE":       1,
		"REMOTE_TO_LOCAL":       2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_transport_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_relay_transport_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{0}
}

// Frame：Tunnel 上的一个帧。oneof 区分帧类型。
// 一次 qrexec 调用 = 一个 RequestHeader + 0..N 个 Data(chunk) + 一个 EndOfStream，
// 出错则以 CallError 收尾。反向回程调用同理，方向由 RequestHeader.direction 标明。
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id：同一 Tunnel 内唯一，串起一次调用的所有帧（含反向回程）。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Handshake
	//	*Frame_RequestHeader
	//	*Frame_Data
	//	*Frame_Eos
	//	*Frame_Error
	//	*Frame_KeepAlive
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_relay_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Frame) GetRequestHeader() *RequestHeader {
	if x != nil {
		if x, ok := x.Kind.(*Frame_RequestHeader); ok {
			return x.RequestHeader
		}
	}
	return nil
}

func (x *Frame) GetData() *DataChunk {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Frame) GetEos() *EndOfStream {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Eos); ok {
			return x.Eos
		}
	}
	return nil
}

func (x *Frame) GetError() *CallError {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Frame) GetKeepAlive() *KeepAlive {
	if x != nil {
		if x, ok := x.Kind.(*Frame_KeepAlive); ok {
			return x.KeepAlive
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,2,opt,name=handshake,proto3,oneof"` // 建流后首帧，交换身份/能力
}

type Frame_RequestHeader struct {
	RequestHeader *RequestHeader `protobuf:"bytes,3,opt,name=request_header,json=requestHeader,proto3,oneof"` // 一次 qrexec 调用的头
}

type Frame_Data struct {
	Data *DataChunk `protobuf:"bytes,4,opt,name=data,proto3,oneof"` // 请求/响应的 payload 分片（可多帧）
}

type Frame_Eos struct {
	Eos *EndOfStream `protobuf:"bytes,5,opt,name=eos,proto3,oneof"` // 某方向数据结束
}

type Frame_Error struct {
	Error *CallError `protobuf:"bytes,6,opt,name=error,proto3,oneof"` // 调用级错误（不影响整条 Tunnel）
}

type Frame_KeepAlive struct {
	KeepAlive *KeepAlive `protobuf:"bytes,7,opt,name=keep_alive,json=keepAlive,proto3,oneof"` // 心跳保活
}

func (*Frame_Handshake) isFrame_Kind() {}

func (*Frame_RequestHeader) isFrame_Kind() {}

func (*Frame_Data) isFrame_Kind() {}

func (*Frame_Eos) isFrame_Kind() {}

func (*Frame_Error) isFrame_Kind() {}

func (*Frame_KeepAlive) isFrame_Kind() {}

// Handshake：建流后 client→server（及 server→client 回应）首帧。
// 承载协议版本与 relay 身份（remote_name 对齐 Qubes RemoteVM 的 remote_name 属性）。
type Handshake struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // 例 "v1"
	RelayName       string                 `protobuf:"bytes,2,opt,name=relay_name,json=relayName,proto3" json:"relay_name,omitempty"`                   // 本地 relay 标识（sys-relay-<zone>）
	RemoteName      string                 `protobuf:"bytes,3,opt,name=remote_name,json=remoteName,proto3" json:"remote_name,omitempty"`                // 目标远端标识（对齐 RemoteVM remote_name）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_relay_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Handshake) GetRelayName() string {
	if x != nil {
		return x.RelayName
	}
	return ""
}

func (x *Handshake) GetRemoteName() string {
	if x != nil {
		return x.RemoteName
	}
	return ""
}

// RequestHeader：一次 qrexec 调用的头。
type RequestHeader struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Direction Direction              `protobuf:"varint,1,opt,name=direction,proto3,enum=qubesair.transport.v1.Direction" json:"direction,omitempty"`
	// qrexec_service：qrexec 服务名（如 qubesair.SomeService、qubes.Gpg）。
	QrexecService string `protobuf:"bytes,2,opt,name=qrexec_service,json=qrexecService,proto3" json:"qrexec_service,omitempty"`
	// source_qube / target_qube：调用的源/目标 qube 名（用于日志与远端 policy 匹配，
	// 【非】授权凭据——授权由两侧 dom0 独立决定）。
	SourceQube string `protobuf:"bytes,3,opt,name=source_qube,json=sourceQube,proto3" json:"source_qube,omitempty"`
	TargetQube string `protobuf:"bytes,4,opt,name=target_qube,json=targetQube,proto3" json:"target_qube,omitempty"`
	// deadline_unix_ms：可选超时（0 表示不设）。
	DeadlineUnixMs int64 `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_relay_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{2}
}

func (x *RequestHeader) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *RequestHeader) GetQrexecService() string {
	if x != nil {
		return x.QrexecService
	}
	return ""
}

func (x *RequestHeader) GetSourceQube() string {
	if x != nil {
		return x.SourceQube
	}
	return ""
}

func (x *RequestHeader) GetTargetQube() string {
	if x != nil {
		return x.TargetQube
	}
	return ""
}

func (x *RequestHeader) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

// DataChunk：请求或响应的一段 payload。同一 request_id 可多帧，按序拼接。
type DataChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stream_id：区分同一调用内的子流。约定：
	//
	//	0 = 请求体（发起方→执行方），1 = 响应体（执行方→发起方），2 = stderr（可选）。
	StreamId      uint32 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_relay_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{3}
}

func (x *DataChunk) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *DataChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// EndOfStream：某个 stream_id 的数据结束。
type EndOfStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndOfStream) Reset() {
	*x = EndOfStream{}
	mi := &file_relay_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndOfStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndOfStream) ProtoMessage() {}

func (x *EndOfStream) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndOfStream.ProtoReflect.Descriptor instead.
func (*EndOfStream) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{4}
}

func (x *EndOfStream) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

// CallError：调用级错误（该 request_id 失败，Tunnel 仍存活）。
type CallError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code：稳定错误码（DENIED=远端 policy 拒绝、TIMEOUT、UNAVAILABLE、INTERNAL…）。
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallError) Reset() {
	*x = CallError{}
	mi := &file_relay_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallError) ProtoMessage() {}

func (x *CallError) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallError.ProtoReflect.Descriptor instead.
func (*CallError) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{5}
}

func (x *CallError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CallError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// KeepAlive：心跳。client 周期发送，server 回应；用于探活与保持 NAT 映射。
// 断线由 client 侧检测并重连（替代 autossh 保活角色）。
type KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"` // 发送方时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	mi := &file_relay_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_relay_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_relay_transport_proto_rawDescGZIP(), []int{6}
}

func (x *KeepAlive) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

var File_relay_transport_proto protoreflect.FileDescriptor

const file_relay_transport_proto_rawDesc = "" +
	"\n" +
	"\x15relay_transport.proto\x12\x15qubesair.transport.v1\"\xac\x03\n" +
	"\x05Frame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\thandshake\x18\x02 \x01(\v2 .qubesair.transport.v1.HandshakeH\x00R\thandshake\x12M\n" +
	"\x0erequest_header\x18\x03 \x01(\v2$.qubesair.transport.v1.RequestHeaderH\x00R\rrequestHeader\x126\n" +
	"\x04data\x18\x04 \x01(\v2 .qubesair.transport.v1.DataChunkH\x00R\x04data\x126\n" +
	"\x03eos\x18\x05 \x01(\v2\".qubesair.transport.v1.EndOfStreamH\x00R\x03eos\x128\n" +
	"\x05error\x18\x06 \x01(\v2 .qubesair.transport.v1.CallErrorH\x00R\x05error\x12A\n" +
	"\n" +
	"keep_alive\x18\a \x01(\v2 .qubesair.transport.v1.KeepAliveH\x00R\tkeepAliveB\x06\n" +
	"\x04kind\"v\n" +
	"\tHandshake\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"relay_name\x18\x02 \x01(\tR\trelayName\x12\x1f\n" +
	"\vremote_name\x18\x03 \x01(\tR\n" +
	"remoteName\"\xe2\x01\n" +
	"\rRequestHeader\x12>\n" +
	"\tdirection\x18\x01 \x01(\x0e2 .qubesair.transport.v1.DirectionR\tdirection\x12%\n" +
	"\x0eqrexec_service\x18\x02 \x01(\tR\rqrexecService\x12\x1f\n" +
	"\vsource_qube\x18\x03 \x01(\tR\n" +
	"sourceQube\x12\x1f\n" +
	"\vtarget_qube\x18\x04 \x01(\tR\n" +
	"targetQube\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"B\n" +
	"\tDataChunk\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"*\n" +
	"\vEndOfStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\"9\n" +
	"\tCallError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\tKeepAlive\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs*P\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOCAL_TO_REMOTE\x10\x01\x12\x13\n" +
	"\x0fREMOTE_TO_LOCAL\x10\x022Z\n" +
	"\x0eRelayTransport\x12H\n" +
	"\x06Tunnel\x12\x1c.qubesair.transport.v1.Frame\x1a\x1c.qubesair.transport.v1.Frame(\x010\x01BIZGgithub.com/slchris/qubes-air/console/internal/transport/relaypb;relaypbb\x06proto3"

var (
	file_relay_transport_proto_rawDescOnce sync.Once
	file_relay_transport_proto_rawDescData []byte
)

func file_relay_transport_proto_rawDescGZIP() []byte {
	file_relay_transport_proto_rawDescOnce.Do(func() {
		file_relay_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_transport_proto_rawDesc), len(file_relay_transport_proto_rawDesc)))
	})
	return file_relay_transport_proto_rawDescData
}

var file_relay_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relay_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_relay_transport_proto_goTypes = []any{
	(Direction)(0),        // 0: qubesair.transport.v1.Direction
	(*Frame)(nil),         // 1: qubesair.transport.v1.Frame
	(*Handshake)(nil),     // 2: qubesair.transport.v1.Handshake
	(*RequestHeader)(nil), // 3: qubesair.transport.v1.RequestHeader
	(*DataChunk)(nil),     // 4: qubesair.transport.v1.DataChunk
	(*EndOfStream)(nil),   // 5: qubesair.transport.v1.EndOfStream
	(*CallError)(nil),     // 6: qubesair.transport.v1.CallError
	(*KeepAlive)(nil),     // 7: qubesair.transport.v1.KeepAlive
}
var file_relay_transport_proto_depIdxs = []int32{
	2, // 0: qubesair.transport.v1.Frame.handshake:type_name -> qubesair.transport.v1.Handshake
	3, // 1: qubesair.transport.v1.Frame.request_header:type_name -> qubesair.transport.v1.RequestHeader
	4, // 2: qubesair.transport.v1.Frame.data:type_name -> qubesair.transport.v1.DataChunk
	5, // 3: qubesair.transport.v1.Frame.eos:type_name -> qubesair.transport.v1.EndOfStream
	6, // 4: qubesair.transport.v1.Frame.error:type_name -> qubesair.transport.v1.CallError
	7, // 5: qubesair.transport.v1.Frame.keep_alive:type_name -> qubesair.transport.v1.KeepAlive
	0, // 6: qubesair.transport.v1.RequestHeader.direction:type_name -> qubesair.transport.v1.Direction
	1, // 7: qubesair.transport.v1.RelayTransport.Tunnel:input_type -> qubesair.transport.v1.Frame
	1, // 8: qubesair.transport.v1.RelayTransport.Tunnel:output_type -> qubesair.transport.v1.Frame
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_relay_transport_proto_init() }
func file_relay_transport_proto_init() {
	if File_relay_transport_proto != nil {
		return
	}
	file_relay_transport_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Handshake)(nil),
		(*Frame_RequestHeader)(nil),
		(*Frame_Data)(nil),
		(*Frame_Eos)(nil),
		(*Frame_Error)(nil),
		(*Frame_KeepAlive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_transport_proto_rawDesc), len(file_relay_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_transport_proto_goTypes,
		DependencyIndexes: file_relay_transport_proto_depIdxs,
		EnumInfos:         file_relay_transport_proto_enumTypes,
		MessageInfos:      file_relay_transport_proto_msgTypes,
	}.Build()
	File_relay_transport_proto = out.File
	file_relay_transport_proto_goTypes = nil
	file_relay_transport_proto_depIdxs = nil
}
