// Package audit records who did what, from where, and how it turned out.
//
// The console had a log line that named the authenticated subject and the HTTP
// method/path, but nothing machine-readable and no source, object or outcome.
// An operator answering "who purged this qube, and did it succeed?" had to
// correlate free-text lines by hand. Entries here are one JSON object per
// mutating request so that question is answerable without parsing prose.
package audit

import (
	"context"
	"io"
	"log/slog"
	"net/http"
	"strings"
	"time"
	"unicode/utf8"
)

// Entry is one audited operator action.
//
// It deliberately carries no request body: mutating bodies can contain secrets
// (a credential value, an API token in the login exchange), and an audit log is
// the last place they should end up. Subject, source, route and object are
// enough to identify the action; the resource itself is not echoed. Nor does
// it carry any request header: the Authorization header and the session cookie
// are credentials, and a denied request is exactly the one most likely to be
// carrying a guessed or stolen one.
type Entry struct {
	// RequestID is generated by the console for this request and returned to
	// the caller, so a reported failure can be matched to its line. It is never
	// taken from the client.
	RequestID string
	// Authenticated reports whether a credential was resolved for the request.
	// When false the entry is rendered as AnonymousSubject with no zone scope
	// (or "unrestricted" when AuthDisabled), whatever Subject and ZoneScope
	// hold: an unauthenticated request must not read as a credential's scope,
	// and forgetting to set this fails towards "anonymous" rather than towards
	// a claimed identity.
	Authenticated bool
	Subject       string
	Source        string
	Method        string
	Route         string
	Object        string
	Status        int
	Outcome       string
	LatencyMS     int64
	// ZoneScope is the object-level allowlist of the acting credential. Empty
	// means fleet-wide; it is recorded so a denial can be attributed both to a
	// subject and to the scope it was acting under.
	ZoneScope []string
	// AuthDisabled reports that the console runs with authentication turned
	// off, so a request without a credential still acted with fleet-wide
	// authority. It only changes how an unauthenticated entry's zone scope
	// reads ("unrestricted" rather than "none"); it grants nothing.
	AuthDisabled bool
}

// AnonymousSubject is the subject recorded for a request no credential was
// resolved for: one refused by authentication, a login attempt, or any request
// while authentication is disabled. The separate "authenticated" field is the
// authoritative flag, so a token that happens to be named "anonymous" cannot be
// confused with the absence of one.
const AnonymousSubject = "anonymous"

// noZoneScope is the zone_scope of an unauthenticated entry. It differs from
// "fleet" on purpose: a request that presented no valid credential acted under
// no scope at all.
const noZoneScope = "none"

// unrestrictedZoneScope is the zone_scope of an unauthenticated entry while
// authentication is disabled. Such a request is not refused by anything and
// can reach every zone, so recording "none" would understate what it could do.
const unrestrictedZoneScope = "unrestricted"

// MaxObjectBytes caps the object field. The object is a path parameter and the
// audit middleware runs before authentication, so it is the one field an
// unauthenticated caller chooses freely; without a cap a single request could
// write a line as long as the server's header limit (1 MiB by default), which a
// line-oriented collector such as journald splits into non-JSON fragments. 128
// bytes is the longest app ID the console accepts and over three times a UUID.
const MaxObjectBytes = 128

// Event is one audit record as it is written: the fields of the JSON line,
// after the anonymous/zone-scope rendering and the object cap. The line and
// every Sink are given the same Event, so a trail read from the log and one
// read from storage cannot disagree about who did what.
type Event struct {
	// Time is the line's "time": when the request finished and was recorded.
	Time          time.Time
	RequestID     string
	Authenticated bool
	// AuthDisabled is on the line as auth_disabled so the stored row, which
	// keeps it, is the line field for field.
	AuthDisabled    bool
	Subject         string
	Source          string
	Method          string
	Route           string
	Object          string
	ObjectTruncated bool
	Status          int
	Outcome         string
	LatencyMS       int64
	// ZoneScope is the rendered scope: "fleet", the comma-joined zone list,
	// "none" or "unrestricted".
	ZoneScope string
}

// Class is how the persisted trail admits an event; see Event.Class.
type Class string

const (
	// ClassFull events are all stored.
	ClassFull Class = "full"
	// ClassSampled events are stored through the unauthenticated budget
	// (PersisterConfig.Budget); the rest are counted into a summary row.
	ClassSampled Class = "sampled"
)

// Class reports how the persisted trail admits e.
//
// Two kinds of event are sampled, because a caller can produce them faster
// than anything bounds on its own:
//
//   - a throttled request (429), authenticated or not. Rate limiting runs
//     after authentication, so every refusal of an authenticated flood is an
//     authenticated event; left in the full class, one token of any scope
//     could push every other subject's records out of the table in
//     milliseconds. Nothing happened on a 429, and its log line keeps it.
//   - a request that proved no credential and did not succeed. Audit runs
//     before authentication and rate limiting, so a caller holding nothing
//     can make these without limit.
//
// Everything else is stored in full: an authenticated event names the
// credential that caused it and is paced by that credential's rate limit, and
// an unauthenticated success is either a login that presented a valid token
// or a request made while authentication is disabled, which acted with full
// authority and is exactly what the trail is for.
func (e Event) Class() Class {
	if e.Status == http.StatusTooManyRequests {
		return ClassSampled
	}
	if e.Authenticated || e.Outcome == OutcomeSuccess {
		return ClassFull
	}
	return ClassSampled
}

// attrs is the line's field list, in the order it has always been written.
func (e Event) attrs() []slog.Attr {
	return []slog.Attr{
		slog.String("request_id", e.RequestID),
		slog.Bool("authenticated", e.Authenticated),
		slog.Bool("auth_disabled", e.AuthDisabled),
		slog.String("subject", e.Subject),
		slog.String("source", e.Source),
		slog.String("method", e.Method),
		slog.String("route", e.Route),
		slog.String("object", e.Object),
		slog.Bool("object_truncated", e.ObjectTruncated),
		slog.Int("status", e.Status),
		slog.String("outcome", e.Outcome),
		slog.Int64("latency_ms", e.LatencyMS),
		slog.String("zone_scope", e.ZoneScope),
	}
}

// Sink receives every event after its line is written. Submit runs on the
// request path, after the response has been produced, so it must not block.
type Sink interface {
	Submit(Event)
}

// Recorder emits entries as JSON lines and hands the same events to its Sink.
type Recorder struct {
	handler slog.Handler
	sink    Sink
	now     func() time.Time
}

// NewRecorder builds a Recorder writing JSON lines to w.
func NewRecorder(w io.Writer) *Recorder {
	return &Recorder{
		handler: slog.NewJSONHandler(w, &slog.HandlerOptions{Level: slog.LevelInfo}),
		now:     time.Now,
	}
}

// WithSink returns a copy of r that also hands every event to sink once its
// line is written. The line comes first so a sink that loses an event (see
// Persister) never costs the log its copy.
func (r *Recorder) WithSink(sink Sink) *Recorder {
	cp := *r
	cp.sink = sink
	return &cp
}

// Record renders e once and writes that Event as the line and to the sink.
//
// The line's "time" is the Event's Time, set here rather than stamped by the
// handler, so the stored copy carries the same instant (two "time" keys would
// be worse than none, so Entry has no time of its own).
//
// The object is cut to MaxObjectBytes and object_truncated says whether it was.
// It is the only field a caller writes freely: the others are fixed by the
// server (the method and template of a registered route, the configured
// credential name and zones, the connection's peer address, the status).
func (r *Recorder) Record(e Entry) {
	ev := e.render(r.now())
	record := slog.NewRecord(ev.Time, slog.LevelInfo, "audit", 0)
	record.AddAttrs(ev.attrs()...)
	// A failed write has nowhere better to be reported than the stream that
	// failed; the sink still gets the event.
	_ = r.handler.Handle(context.Background(), record)
	if r.sink != nil {
		r.sink.Submit(ev)
	}
}

// render applies the rendering rules to e: an unauthenticated entry reads as
// the anonymous subject with no zone scope (or "unrestricted" while
// authentication is disabled), whatever Subject and ZoneScope hold, the object
// is capped, and every string is made valid UTF-8 the way the JSON line
// writes it.
func (e Entry) render(at time.Time) Event {
	subject, scope := e.Subject, zoneScope(e.ZoneScope)
	if !e.Authenticated {
		subject, scope = AnonymousSubject, noZoneScope
		if e.AuthDisabled {
			scope = unrestrictedZoneScope
		}
	}
	object, truncated := boundObject(e.Object)
	return Event{
		Time:            at,
		RequestID:       validUTF8(e.RequestID),
		Authenticated:   e.Authenticated,
		AuthDisabled:    e.AuthDisabled,
		Subject:         validUTF8(subject),
		Source:          validUTF8(e.Source),
		Method:          validUTF8(e.Method),
		Route:           validUTF8(e.Route),
		Object:          validUTF8(object),
		ObjectTruncated: truncated,
		Status:          e.Status,
		Outcome:         validUTF8(e.Outcome),
		LatencyMS:       e.LatencyMS,
		ZoneScope:       validUTF8(scope),
	}
}

// validUTF8 replaces each byte that is not part of a valid UTF-8 sequence with
// U+FFFD, one for one. That is exactly what the JSON line shows for such a
// byte, so doing it here, before the line is written, is what keeps a stored
// copy equal to the line: the object is a path parameter, and "%FF" in a URL
// is all it takes to put such a byte there.
func validUTF8(s string) string {
	if utf8.ValidString(s) {
		return s
	}
	var b strings.Builder
	b.Grow(len(s) + 2*utf8.UTFMax)
	for i := 0; i < len(s); {
		r, size := utf8.DecodeRuneInString(s[i:])
		if r == utf8.RuneError && size == 1 {
			b.WriteRune(utf8.RuneError)
		} else {
			b.WriteString(s[i : i+size])
		}
		i += size
	}
	return b.String()
}

// zoneScope renders a nil/empty allowlist as the fleet-wide label: "fleet"
// rather than an empty list, because an absent field reads as "unknown" in a
// log, and the difference between no restriction and a restriction that
// matched nothing matters during an incident.
func zoneScope(zones []string) string {
	if len(zones) == 0 {
		return "fleet"
	}
	return strings.Join(zones, ",")
}

// boundObject cuts object to at most MaxObjectBytes, on a UTF-8 character
// boundary so the kept prefix is not ended by half a character. Bytes that are
// not valid UTF-8 count as one-byte characters; the JSON encoder escapes them
// (and every control character), so the cut value cannot break the line.
func boundObject(object string) (string, bool) {
	if len(object) <= MaxObjectBytes {
		return object, false
	}
	cut := 0
	for i := range object {
		if i > MaxObjectBytes {
			break
		}
		cut = i
	}
	return object[:cut], true
}

// Outcome values. They are exported because callers and tests switch on them;
// a typo in a string literal here would silently stop matching.
const (
	OutcomeSuccess     = "success"
	OutcomeDenied      = "denied"
	OutcomeClientError = "client_error"
	OutcomeError       = "error"
)

// Outcome classifies an HTTP status for the audit trail: OutcomeDenied
// specifically marks an authorization failure, which is the line an operator
// greps for.
func Outcome(status int) string {
	switch {
	case status >= 200 && status < 300:
		return OutcomeSuccess
	case status == http.StatusUnauthorized || status == http.StatusForbidden:
		return OutcomeDenied
	case status >= 400 && status < 500:
		return OutcomeClientError
	default:
		return OutcomeError
	}
}

// Object extracts the resource identifier from the request's path parameters.
// "id" is the convention across the API; "app" is the one nested launch route.
func Object(params func(string) string) string {
	if id := strings.TrimSpace(params("id")); id != "" {
		return id
	}
	return strings.TrimSpace(params("app"))
}
