// Package audit records who did what, from where, and how it turned out.
//
// The console had a log line that named the authenticated subject and the HTTP
// method/path, but nothing machine-readable and no source, object or outcome.
// An operator answering "who purged this qube, and did it succeed?" had to
// correlate free-text lines by hand. Entries here are one JSON object per
// mutating request so that question is answerable without parsing prose.
package audit

import (
	"context"
	"io"
	"log/slog"
	"net/http"
	"strings"
)

// Entry is one audited operator action.
//
// It deliberately carries no request body: mutating bodies can contain secrets
// (a credential value, an API token in the login exchange), and an audit log is
// the last place they should end up. Subject, source, route and object are
// enough to identify the action; the resource itself is not echoed. Nor does
// it carry any request header: the Authorization header and the session cookie
// are credentials, and a denied request is exactly the one most likely to be
// carrying a guessed or stolen one.
type Entry struct {
	// RequestID is generated by the console for this request and returned to
	// the caller, so a reported failure can be matched to its line. It is never
	// taken from the client.
	RequestID string
	// Authenticated reports whether a credential was resolved for the request.
	// When false the entry is rendered as AnonymousSubject with no zone scope,
	// whatever Subject and ZoneScope hold: an unauthenticated request must not
	// read as fleet-wide, and forgetting to set this fails towards "anonymous"
	// rather than towards a claimed identity.
	Authenticated bool
	Subject       string
	Source        string
	Method        string
	Route         string
	Object        string
	Status        int
	Outcome       string
	LatencyMS     int64
	// ZoneScope is the object-level allowlist of the acting credential. Empty
	// means fleet-wide; it is recorded so a denial can be attributed both to a
	// subject and to the scope it was acting under.
	ZoneScope []string
}

// AnonymousSubject is the subject recorded for a request no credential was
// resolved for: one refused by authentication, a login attempt, or any request
// while authentication is disabled. The separate "authenticated" field is the
// authoritative flag, so a token that happens to be named "anonymous" cannot be
// confused with the absence of one.
const AnonymousSubject = "anonymous"

// noZoneScope is the zone_scope of an unauthenticated entry. It differs from
// "fleet" on purpose: a request that presented no valid credential acted under
// no scope at all.
const noZoneScope = "none"

// MaxObjectBytes caps the object field. The object is a path parameter and the
// audit middleware runs before authentication, so it is the one field an
// unauthenticated caller chooses freely; without a cap a single request could
// write a line as long as the server's header limit (1 MiB by default), which a
// line-oriented collector such as journald splits into non-JSON fragments. 128
// bytes is the longest app ID the console accepts and over three times a UUID.
const MaxObjectBytes = 128

// Recorder emits entries as JSON lines.
type Recorder struct {
	logger *slog.Logger
}

// NewRecorder builds a Recorder writing JSON lines to w.
func NewRecorder(w io.Writer) *Recorder {
	return &Recorder{
		logger: slog.New(slog.NewJSONHandler(w, &slog.HandlerOptions{Level: slog.LevelInfo})),
	}
}

// Record writes one entry. The handler stamps the time, so it is not carried on
// Entry (two "time" keys would be worse than none).
//
// The object is cut to MaxObjectBytes and object_truncated says whether it was.
// It is the only field a caller writes freely: the others are fixed by the
// server (the method and template of a registered route, the configured
// credential name and zones, the connection's peer address, the status).
func (r *Recorder) Record(e Entry) {
	subject, scope := e.Subject, zoneScope(e.ZoneScope)
	if !e.Authenticated {
		subject, scope = AnonymousSubject, noZoneScope
	}
	object, truncated := boundObject(e.Object)
	r.logger.LogAttrs(context.Background(), slog.LevelInfo, "audit",
		slog.String("request_id", e.RequestID),
		slog.Bool("authenticated", e.Authenticated),
		slog.String("subject", subject),
		slog.String("source", e.Source),
		slog.String("method", e.Method),
		slog.String("route", e.Route),
		slog.String("object", object),
		slog.Bool("object_truncated", truncated),
		slog.Int("status", e.Status),
		slog.String("outcome", e.Outcome),
		slog.Int64("latency_ms", e.LatencyMS),
		// "fleet" rather than an empty list: an absent field reads as "unknown"
		// in a log, and the difference between no restriction and a restriction
		// that matched nothing matters during an incident.
		slog.String("zone_scope", scope),
	)
}

// zoneScope renders a nil/empty allowlist as the fleet-wide label.
func zoneScope(zones []string) string {
	if len(zones) == 0 {
		return "fleet"
	}
	return strings.Join(zones, ",")
}

// boundObject cuts object to at most MaxObjectBytes, on a UTF-8 character
// boundary so the kept prefix is not ended by half a character. Bytes that are
// not valid UTF-8 count as one-byte characters; the JSON encoder escapes them
// (and every control character), so the cut value cannot break the line.
func boundObject(object string) (string, bool) {
	if len(object) <= MaxObjectBytes {
		return object, false
	}
	cut := 0
	for i := range object {
		if i > MaxObjectBytes {
			break
		}
		cut = i
	}
	return object[:cut], true
}

// Outcome values. They are exported because callers and tests switch on them;
// a typo in a string literal here would silently stop matching.
const (
	OutcomeSuccess     = "success"
	OutcomeDenied      = "denied"
	OutcomeClientError = "client_error"
	OutcomeError       = "error"
)

// Outcome classifies an HTTP status for the audit trail: OutcomeDenied
// specifically marks an authorization failure, which is the line an operator
// greps for.
func Outcome(status int) string {
	switch {
	case status >= 200 && status < 300:
		return OutcomeSuccess
	case status == http.StatusUnauthorized || status == http.StatusForbidden:
		return OutcomeDenied
	case status >= 400 && status < 500:
		return OutcomeClientError
	default:
		return OutcomeError
	}
}

// Object extracts the resource identifier from the request's path parameters.
// "id" is the convention across the API; "app" is the one nested launch route.
func Object(params func(string) string) string {
	if id := strings.TrimSpace(params("id")); id != "" {
		return id
	}
	return strings.TrimSpace(params("app"))
}
