package service

import (
	"fmt"
	"strings"

	"github.com/slchris/qubes-air/console/internal/pki"
)

// agentInstallDir is where the agent's mTLS material lands on the remote.
const agentInstallDir = "/etc/qubes-air"

// RenderAgentUserData produces the cloud-init user-data that installs an
// agent's identity on first boot.
//
// This is the delivery half of certificate issuance: the bundle is useless
// until it reaches the remote, and cloud-init is the only channel that exists
// before the agent is running.
//
// The output is deliberately a cloud-config document rather than a script.
// write_files is declarative, idempotent, and sets permissions atomically —
// a shell script doing the same has to get ordering and umask right, and gets
// them wrong quietly.
func RenderAgentUserData(remoteName string, bundle *pki.Bundle, listen string) (string, error) {
	if bundle == nil {
		return "", fmt.Errorf("no certificate bundle to deliver")
	}
	if remoteName == "" {
		return "", fmt.Errorf("remote name is required: the agent reports it and qubesair.Ping returns it")
	}
	if listen == "" {
		listen = "0.0.0.0:8443"
	}

	// The key is mode 0600 and the others 0644. The distinction matters: a
	// world-readable private key on a multi-user host hands the agent's identity
	// to every local account, which is the one thing certificate issuance was
	// supposed to make revocable rather than ambient.
	var b strings.Builder
	b.WriteString("#cloud-config\n")
	b.WriteString("# Generated by the Qubes Air console — installs this agent's mTLS identity.\n")
	b.WriteString("#\n")
	b.WriteString("# NOTE: this document contains the agent's PRIVATE KEY. On Proxmox, cloud-init\n")
	b.WriteString("# data is readable through the API by anyone holding VM.Config.Cloudinit, so\n")
	b.WriteString("# that permission is equivalent to holding every agent identity it delivered.\n")
	b.WriteString("# See docs/remote-agent-design.md for why this trade-off was accepted.\n")
	b.WriteString("write_files:\n")

	writeFile(&b, agentInstallDir+"/ca.pem", "0644", bundle.CAPEM)
	writeFile(&b, agentInstallDir+"/agent.pem", "0644", bundle.CertPEM)
	writeFile(&b, agentInstallDir+"/agent-key.pem", "0600", bundle.KeyPEM)
	writeFile(&b, agentInstallDir+"/agent.env",
		"0644", fmt.Sprintf("QUBESAIR_REMOTE_NAME=%s\nQUBESAIR_LISTEN=%s\n", remoteName, listen))

	// Start the agent only after the files exist. cloud-init runs runcmd after
	// write_files, so the ordering is guaranteed rather than hoped for.
	b.WriteString("runcmd:\n")
	b.WriteString("  - [ chown, -R, 'root:root', " + agentInstallDir + " ]\n")
	b.WriteString("  - [ chmod, '0750', " + agentInstallDir + " ]\n")
	b.WriteString("  - [ systemctl, enable, --now, qubes-air-agent ]\n")

	return b.String(), nil
}

// writeFile appends one write_files entry.
//
// Content is emitted as a YAML literal block, which needs no escaping of quotes
// or backslashes — PEM is multi-line and would otherwise have to be quoted
// correctly every time, and a single mistake produces a file that looks right
// and does not parse.
func writeFile(b *strings.Builder, path, mode, content string) {
	fmt.Fprintf(b, "  - path: %s\n", path)
	fmt.Fprintf(b, "    permissions: '%s'\n", mode)
	b.WriteString("    owner: root:root\n")
	b.WriteString("    content: |\n")
	for _, line := range strings.Split(strings.TrimRight(content, "\n"), "\n") {
		fmt.Fprintf(b, "      %s\n", line)
	}
}

// SnippetVolumeID is the terraform user_data_file_id for a qube's snippet.
//
// Proxmox addresses a snippet as "<datastore>:snippets/<file>". The datastore
// must declare the "snippets" content type, or PVE will not resolve the volume
// even when the file is present on disk.
func SnippetVolumeID(datastore, qubeName string) string {
	if datastore == "" {
		datastore = "local"
	}
	return fmt.Sprintf("%s:snippets/qubes-air-%s.yaml", datastore, qubeName)
}

// SnippetFileName is the on-disk name matching SnippetVolumeID.
func SnippetFileName(qubeName string) string {
	return fmt.Sprintf("qubes-air-%s.yaml", qubeName)
}
